package raspivision;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import edu.wpi.first.vision.VisionPipeline;
import org.opencv.core.*;

import org.opencv.imgproc.*;

/**
 * VisionTargetPipeline class.
 *
 * <p>An OpenCV pipeline generated by GRIP.
 *
 * @author GRIP
 */
public class VisionTargetPipeline implements VisionPipeline
{

    //Outputs
    private Mat input = new Mat();
    private Mat hslThresholdOutput = new Mat();
    private ArrayList<MatOfPoint> findContoursOutput = new ArrayList<>();
    private ArrayList<MatOfPoint> filterContoursOutput = new ArrayList<>();
    private ArrayList<MatOfPoint> convexHullsOutput = new ArrayList<>();
    private List<TargetData> detectedTargets = new ArrayList<>();
    private TargetData selectedTarget = null;

    static
    {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }

    /**
     * This is the primary method that runs the entire pipeline and updates the outputs.
     */
    public void process(Mat source0)
    {
        long start = System.currentTimeMillis();

        try
        {
            // Clear the detected targets
            detectedTargets.clear();
            selectedTarget = null;

            input = source0;
            // Step HSL_Threshold0:
            Mat hslThresholdInput = source0;
            double[] hslThresholdHue = { 69.31654676258991, 93.63636363636363 };
            double[] hslThresholdSaturation = { 90.52158273381295, 255.0 };
            double[] hslThresholdLuminance = { 112.36510791366906, 255.0 };
            hslThreshold(hslThresholdInput, hslThresholdHue, hslThresholdSaturation, hslThresholdLuminance,
                hslThresholdOutput);

            // Step Find_Contours0:
            Mat findContoursInput = hslThresholdOutput;
            findContours(findContoursInput, true, findContoursOutput);
            System.out.printf("Detected %d vision targets\n", findContoursOutput.size());

            // Step Filter_Contours0:
            ArrayList<MatOfPoint> filterContoursContours = findContoursOutput;
            double filterContoursMinArea = 1000.0;
            double filterContoursMinPerimeter = 0.0;
            double filterContoursMinWidth = 0.0;
            double filterContoursMaxWidth = 100000.0;
            double filterContoursMinHeight = 0.0;
            double filterContoursMaxHeight = 100000.0;
            double[] filterContoursSolidity = { 0, 100 };
            double filterContoursMaxVertices = 1000000.0;
            double filterContoursMinVertices = 0.0;
            double filterContoursMinRatio = 0.0;
            double filterContoursMaxRatio = 1000.0;
            filterContours(filterContoursContours, filterContoursMinArea, filterContoursMinPerimeter,
                filterContoursMinWidth, filterContoursMaxWidth, filterContoursMinHeight, filterContoursMaxHeight,
                filterContoursSolidity, filterContoursMaxVertices, filterContoursMinVertices, filterContoursMinRatio,
                filterContoursMaxRatio, filterContoursOutput);

            System.out.printf("Detected %d filtered vision targets\n", filterContoursContours.size());

            // Step Convex_Hulls0:
            ArrayList<MatOfPoint> convexHullsContours = filterContoursOutput;
            convexHulls(convexHullsContours, convexHullsOutput);

            if (convexHullsOutput.isEmpty())
            {
                return;
            }

            // Convert contours to vision targets
            ArrayList<VisionTarget> visionTargets = convexHullsOutput.stream().map(this::mapContourToVisionTarget)
                .sorted(this::compareVisionTargets).collect(Collectors.toCollection(ArrayList::new));

            // Trim mismatched targets
            while (!visionTargets.get(0).isLeftTarget)
            {
                visionTargets.remove(0);
                if (visionTargets.isEmpty())
                {
                    return;
                }
            }
            while (visionTargets.get(visionTargets.size() - 1).isLeftTarget)
            {
                visionTargets.remove(visionTargets.size() - 1);
                if (visionTargets.isEmpty())
                {
                    return;
                }
            }

            if (isValid(visionTargets))
            {
                detectedTargets = detectTargets(visionTargets);
                selectedTarget = detectedTargets.stream().min(Comparator.comparingInt(e -> Math.abs(e.x)))
                    .orElseThrow(IllegalStateException::new);
            }
        }
        finally
        {
            long elapsed = System.currentTimeMillis() - start;
            if (elapsed >= 100)
            {
                System.err.println("Vision pipeline took too long!");
            }
        }
    }

    public Mat getHslThresholdOutput()
    {
        return hslThresholdOutput;
    }

    public TargetData getSelectedTarget()
    {
        return selectedTarget;
    }

    public List<TargetData> getDetectedTargets()
    {
        return detectedTargets;
    }

    public Mat getInput()
    {
        return input;
    }

    /**
     * This method is a generated getter for the output of a Convex_Hulls.
     *
     * @return ArrayList<MatOfPoint> output from Convex_Hulls.
     */
    public ArrayList<MatOfPoint> convexHullsOutput()
    {
        return convexHullsOutput;
    }

    /**
     * Segment an image based on hue, saturation, and luminance ranges.
     *
     * @param input The image on which to perform the HSL threshold.
     * @param hue   The min and max hue
     * @param sat   The min and max saturation
     * @param lum   The min and max luminance
     * @param out   The image in which to store the output.
     */
    private void hslThreshold(Mat input, double[] hue, double[] sat, double[] lum, Mat out)
    {
        Imgproc.cvtColor(input, out, Imgproc.COLOR_BGR2HLS);
        Core.inRange(out, new Scalar(hue[0], lum[0], sat[0]), new Scalar(hue[1], lum[1], sat[1]), out);
    }

    private void findContours(Mat input, boolean externalOnly, List<MatOfPoint> contours)
    {
        Mat hierarchy = new Mat();
        contours.clear();
        int mode;
        if (externalOnly)
        {
            mode = Imgproc.RETR_EXTERNAL;
        }
        else
        {
            mode = Imgproc.RETR_LIST;
        }
        int method = Imgproc.CHAIN_APPROX_SIMPLE;
        Imgproc.findContours(input, contours, hierarchy, mode, method);
    }

    /**
     * Filters out contours that do not meet certain criteria.
     *
     * @param inputContours  is the input list of contours
     * @param output         is the the output list of contours
     * @param minArea        is the minimum area of a contour that will be kept
     * @param minPerimeter   is the minimum perimeter of a contour that will be kept
     * @param minWidth       minimum width of a contour
     * @param maxWidth       maximum width
     * @param minHeight      minimum height
     * @param maxHeight      maximimum height
     * @param solidity       the minimum and maximum solidity of a contour
     * @param minVertexCount minimum vertex Count of the contours
     * @param maxVertexCount maximum vertex Count
     * @param minRatio       minimum ratio of width to height
     * @param maxRatio       maximum ratio of width to height
     */
    private void filterContours(List<MatOfPoint> inputContours, double minArea, double minPerimeter, double minWidth,
        double maxWidth, double minHeight, double maxHeight, double[] solidity, double maxVertexCount,
        double minVertexCount, double minRatio, double maxRatio, List<MatOfPoint> output)
    {
        final MatOfInt hull = new MatOfInt();
        output.clear();
        //operation
        for (int i = 0; i < inputContours.size(); i++)
        {
            final MatOfPoint contour = inputContours.get(i);
            final Rect bb = Imgproc.boundingRect(contour);
            if (bb.width < minWidth || bb.width > maxWidth)
                continue;
            if (bb.height < minHeight || bb.height > maxHeight)
                continue;
            final double area = Imgproc.contourArea(contour);
            if (area < minArea)
                continue;
            if (Imgproc.arcLength(new MatOfPoint2f(contour.toArray()), true) < minPerimeter)
                continue;
            Imgproc.convexHull(contour, hull);
            MatOfPoint mopHull = new MatOfPoint();
            mopHull.create((int) hull.size().height, 1, CvType.CV_32SC2);
            for (int j = 0; j < hull.size().height; j++)
            {
                int index = (int) hull.get(j, 0)[0];
                double[] point = new double[] { contour.get(index, 0)[0], contour.get(index, 0)[1] };
                mopHull.put(j, 0, point);
            }
            final double solid = 100 * area / Imgproc.contourArea(mopHull);
            if (solid < solidity[0] || solid > solidity[1])
                continue;
            if (contour.rows() < minVertexCount || contour.rows() > maxVertexCount)
                continue;
            final double ratio = bb.width / (double) bb.height;
            if (ratio < minRatio || ratio > maxRatio)
                continue;
            output.add(contour);
        }
    }

    /**
     * Compute the convex hulls of contours.
     *
     * @param inputContours  The contours on which to perform the operation.
     * @param outputContours The contours where the output will be stored.
     */
    private void convexHulls(List<MatOfPoint> inputContours, ArrayList<MatOfPoint> outputContours)
    {
        final MatOfInt hull = new MatOfInt();
        outputContours.clear();
        for (int i = 0; i < inputContours.size(); i++)
        {
            final MatOfPoint contour = inputContours.get(i);
            final MatOfPoint mopHull = new MatOfPoint();
            Imgproc.convexHull(contour, hull);
            mopHull.create((int) hull.size().height, 1, CvType.CV_32SC2);
            for (int j = 0; j < hull.size().height; j++)
            {
                int index = (int) hull.get(j, 0)[0];
                double[] point = new double[] { contour.get(index, 0)[0], contour.get(index, 0)[1] };
                mopHull.put(j, 0, point);
            }
            outputContours.add(mopHull);
        }
    }

    /**
     * Checks if the list of targets is valid.
     *
     * @param targets The targets to validate.
     * @return True if valid, false otherwise.
     */
    private boolean isValid(List<VisionTarget> targets)
    {
        // Invalid if no targets or odd number of targets.
        if (targets.size() == 0 || targets.size() % 2 == 1)
        {
            return false;
        }
        // Verify that there are alternating pairs of targets. (Left right left right)
        for (int i = 0; i < targets.size(); i += 2)
        {
            VisionTarget left = targets.get(i);
            VisionTarget right = targets.get(i + 1);
            if (!left.isLeftTarget || right.isLeftTarget)
            {
                return false;
            }
        }
        return true;
    }

    private double getCorrectedAngle(RotatedRect calculatedRect)
    {
        if (calculatedRect.size.width < calculatedRect.size.height)
        {
            return calculatedRect.angle + 180;
        }
        else
        {
            return calculatedRect.angle + 90;
        }
    }

    private List<TargetData> detectTargets(List<VisionTarget> targets)
    {
        List<TargetData> targetDatas = new ArrayList<>(); // Yes I know datas isn't a word.
        // Pair vision targets and get the enclosing bounding box.
        for (int i = 0; i < targets.size(); i += 2)
        {
            VisionTarget left = targets.get(i);
            VisionTarget right = targets.get(i + 1);
            int leftBound = left.x - left.w / 2;
            int rightBound = right.x + right.w / 2;
            int topBound = Math.max(left.y + left.h / 2, right.y + right.h / 2);
            int bottomBound = Math.min(left.y - left.h / 2, right.y - right.h / 2);
            TargetData data = new TargetData((leftBound + rightBound) / 2, (topBound + bottomBound) / 2,
                rightBound - leftBound, Math.abs(bottomBound - topBound));
            targetDatas.add(data);
        }
        return targetDatas;
    }

    private VisionTarget mapContourToVisionTarget(MatOfPoint m)
    {
        MatOfPoint2f contour = new MatOfPoint2f();
        m.convertTo(contour, CvType.CV_32F);
        RotatedRect rect = Imgproc.minAreaRect(contour);

        VisionTarget target = new VisionTarget();
        target.isLeftTarget = getCorrectedAngle(rect) <= 90;
        target.x = round(rect.center.x);
        target.y = round(rect.center.y);
        target.w = round(rect.size.width);
        target.h = round(rect.size.height);
        return target;
    }

    private int round(double d)
    {
        return (int) (Math.floor(d + 0.5));
    }

    private int compareVisionTargets(VisionTarget target1, VisionTarget target2)
    {
        return Integer.compare(target1.x, target2.x);
    }

    /**
     * Represents a single retroflective tape.
     */
    private class VisionTarget
    {
        public boolean isLeftTarget;
        public int x, y, w, h;

        public boolean equals(Object o)
        {
            if (!(o instanceof VisionTarget))
                return false;
            VisionTarget target = (VisionTarget) o;
            return target.isLeftTarget == isLeftTarget && target.x == x && target.y == y && target.w == w
                && target.h == h;
        }
    }
}

